-- MySQL Script generated by MySQL Workbench
-- Thu Dec 12 22:13:57 2019
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema aparso9db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aparso9db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aparso9db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `aparso9db` ;

-- -----------------------------------------------------
-- Table `aparso9db`.`accessory`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`accessory` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`accessory` (
  `idACCESSORY` INT(11) NOT NULL,
  `type` VARCHAR(45) NULL DEFAULT NULL,
  `console` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idACCESSORY`),
  CONSTRAINT `accessoryID`
    FOREIGN KEY (`idACCESSORY`)
    REFERENCES `aparso9db`.`product` (`idPRODUCT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`corporate`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`corporate` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`corporate` (
  `CID` INT(11) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(2) NULL,
  `zip` VARCHAR(45) NULL,
  `phoneNo` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`CID`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`customers`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`customers` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`customers` (
  `idCUSTOMER` INT(11) NOT NULL,
  `fName` VARCHAR(12) NULL DEFAULT NULL,
  `lName` VARCHAR(15) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(2) NULL,
  `zip` VARCHAR(5) NULL,
  `phoneNo` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idCUSTOMER`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`district`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`district` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`district` (
  `DistrictID` INT(11) NOT NULL,
  `corpID` INT NOT NULL,
  PRIMARY KEY (`DistrictID`),
  INDEX `corpID_idx` (`corpID` ASC) VISIBLE,
  CONSTRAINT `corpID`
    FOREIGN KEY (`corpID`)
    REFERENCES `aparso9db`.`corporate` (`CID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`employees`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`employees` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`employees` (
  `SSN` VARCHAR(9) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(2) NULL,
  `zip` VARCHAR(5) NULL,
  `fname` VARCHAR(12) NULL DEFAULT NULL,
  `lName` VARCHAR(15) NULL DEFAULT NULL,
  `bDate` DATE NULL DEFAULT NULL,
  `salary` INT(11) NOT NULL,
  `sex` VARCHAR(1) NULL DEFAULT NULL,
  `position` VARCHAR(45) NULL,
  `managerSSN` VARCHAR(9) NULL,
  `gameStoreID` INT NULL,
  `districtID` INT NULL,
  `corporateID` INT NULL,
  PRIMARY KEY (`SSN`),
  INDEX `Manager_idx` (`managerSSN` ASC) VISIBLE,
  INDEX `GameStoreID_idx` (`gameStoreID` ASC) VISIBLE,
  INDEX `District_idx` (`districtID` ASC) VISIBLE,
  INDEX `Corporate_idx` (`corporateID` ASC) VISIBLE,
  CONSTRAINT `Manager`
    FOREIGN KEY (`managerSSN`)
    REFERENCES `aparso9db`.`employees` (`SSN`),
  CONSTRAINT `GameStoreID`
    FOREIGN KEY (`gameStoreID`)
    REFERENCES `aparso9db`.`game_store` (`idGAME_STORE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `District`
    FOREIGN KEY (`districtID`)
    REFERENCES `aparso9db`.`district` (`DistrictID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `Corporate`
    FOREIGN KEY (`corporateID`)
    REFERENCES `aparso9db`.`corporate` (`CID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`game`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`game` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`game` (
  `idGAME` INT(11) NOT NULL,
  `console` VARCHAR(25) NULL DEFAULT NULL,
  `rating` VARCHAR(5) NULL DEFAULT NULL,
  `publisher` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`idGAME`),
  CONSTRAINT `gameID`
    FOREIGN KEY (`idGAME`)
    REFERENCES `aparso9db`.`product` (`idPRODUCT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`game_store`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`game_store` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`game_store` (
  `idGAME_STORE` INT(11) NOT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(2) NULL,
  `zip` VARCHAR(5) NULL,
  `phoneNo` VARCHAR(10) NULL DEFAULT NULL,
  `distID` INT NOT NULL,
  PRIMARY KEY (`idGAME_STORE`),
  INDEX `districtID_idx` (`distID` ASC) VISIBLE,
  CONSTRAINT `districtID`
    FOREIGN KEY (`distID`)
    REFERENCES `aparso9db`.`district` (`DistrictID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`has`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`has` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`has` (
  `GameStoreID` INT(11) NOT NULL,
  `CustomerID` INT(11) NOT NULL,
  PRIMARY KEY (`GameStoreID`, `CustomerID`),
  INDEX `CustomerID_idx` (`CustomerID` ASC) VISIBLE,
  CONSTRAINT `CustomerID`
    FOREIGN KEY (`CustomerID`)
    REFERENCES `aparso9db`.`customers` (`idCUSTOMER`),
  CONSTRAINT `Game_StoreID`
    FOREIGN KEY (`GameStoreID`)
    REFERENCES `aparso9db`.`game_store` (`idGAME_STORE`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`product`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`product` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`product` (
  `idPRODUCT` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `price` DECIMAL(10,2) NULL DEFAULT NULL,
  `isReserved` VARCHAR(1) NOT NULL,
  `gameStoreID` INT NOT NULL,
  PRIMARY KEY (`idPRODUCT`),
  INDEX `gsID_idx` (`gameStoreID` ASC) VISIBLE,
  CONSTRAINT `gsID`
    FOREIGN KEY (`gameStoreID`)
    REFERENCES `aparso9db`.`game_store` (`idGAME_STORE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`reserve`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`reserve` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`reserve` (
  `idRESERVATION` INT(11) NOT NULL,
  `CustoID` INT(11) NOT NULL,
  `ProdID` INT(11) NOT NULL,
  PRIMARY KEY (`idRESERVATION`),
  INDEX `CustoID_idx` (`CustoID` ASC) VISIBLE,
  INDEX `ProdID_idx` (`ProdID` ASC) VISIBLE,
  UNIQUE INDEX `ProdID_UNIQUE` (`ProdID` ASC) VISIBLE,
  CONSTRAINT `CustoID`
    FOREIGN KEY (`CustoID`)
    REFERENCES `aparso9db`.`customers` (`idCUSTOMER`),
  CONSTRAINT `ProdID`
    FOREIGN KEY (`ProdID`)
    REFERENCES `aparso9db`.`product` (`idPRODUCT`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`supplier`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`supplier` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`supplier` (
  `idSUPPLIER` INT(11) NOT NULL,
  `supplierName` VARCHAR(45) NULL DEFAULT NULL,
  `address` VARCHAR(45) NULL DEFAULT NULL,
  `city` VARCHAR(45) NULL,
  `state` VARCHAR(2) NULL,
  `zip` VARCHAR(5) NULL,
  `phoneNo` VARCHAR(10) NULL DEFAULT NULL,
  PRIMARY KEY (`idSUPPLIER`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aparso9db`.`supplies`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `aparso9db`.`supplies` ;

CREATE TABLE IF NOT EXISTS `aparso9db`.`supplies` (
  `productID` INT NOT NULL,
  `supplierID` INT NOT NULL,
  PRIMARY KEY (`productID`, `supplierID`),
  INDEX `supplier_idx` (`supplierID` ASC) VISIBLE,
  CONSTRAINT `product`
    FOREIGN KEY (`productID`)
    REFERENCES `aparso9db`.`product` (`idPRODUCT`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `supplier`
    FOREIGN KEY (`supplierID`)
    REFERENCES `aparso9db`.`supplier` (`idSUPPLIER`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
